# Generated by Django 5.2 on 2025-06-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_number', models.CharField(max_length=15)),
                ('res_name', models.CharField(max_length=100)),
                ('res_address', models.TextField()),
                ('fssai_no', models.CharField(max_length=50)),
                ('res_picture', models.ImageField(upload_to='restaurant_pics/')),
                ('res_cat', models.CharField(choices=[('preorder', 'Preorder Kitchen'), ('normal', 'Instant Restaurant')], max_length=10)),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
