# Generated by Django 4.2 on 2025-06-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(default='Provide Description..'),
        ),
    ]
