# Generated by Django 5.2 on 2025-06-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_thali_thaliitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thali',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='thaliitem',
            name='thali',
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('dishName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('time_limit', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Restaurant.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Thali',
        ),
        migrations.DeleteModel(
            name='ThaliItem',
        ),
    ]
