# Generated by Django 4.2 on 2025-06-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_menu_delete_meal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
