# Generated by Django 5.2 on 2025-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_pics/'),
        ),
    ]
